/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.java.cmet.ac.co2reader;
import com.mycompany.java.cmet.ac.co2reader.clientSide;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author fahim
 */
public class viewRecords extends javax.swing.JFrame {

    /**
     * Creates new form viewRecords
     */
    public viewRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recordsTitle = new javax.swing.JLabel();
        heading1 = new javax.swing.JLabel();
        viewUpdateRecordsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        heading2 = new javax.swing.JLabel();
        logoutRecordsMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        recordsTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        recordsTitle.setText("CO2 PPM Records");

        heading1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        heading1.setText("In this section, you are able to view CO2 parts per million records that were previously input.");

        viewUpdateRecordsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewUpdateRecordsButton.setText("View/update records");
        viewUpdateRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdateRecordsButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setText("Go back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        heading2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        heading2.setText("You are also able to update records as needed.");

        logoutRecordsMenu.setText("Logout");
        logoutRecordsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutRecordsMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewUpdateRecordsButton)
                        .addGap(108, 108, 108)
                        .addComponent(backButton)
                        .addGap(390, 390, 390))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(recordsTitle))
                            .addComponent(heading1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(heading2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(194, 194, 194)
                        .addComponent(logoutRecordsMenu)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(recordsTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutRecordsMenu)))
                .addGap(18, 18, 18)
                .addComponent(heading1)
                .addGap(18, 18, 18)
                .addComponent(heading2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewUpdateRecordsButton)
                    .addComponent(backButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        mainMenu goToMenuPage = new mainMenu();
        goToMenuPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewUpdateRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdateRecordsButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\fahim\\OneDrive - Cardiff Metropolitan University\\Year 2\\Object-Oriented Programming\\java.cmet.ac.co2Reader"));

        int choice = fileChooser.showOpenDialog(null);
        
        if(choice == JFileChooser.APPROVE_OPTION){
            
            try {
                File MyFile = new File(fileChooser.getSelectedFile().getAbsolutePath());
                Desktop.getDesktop().open(MyFile);
            } catch (IOException ex) {
                Logger.getLogger(viewRecords.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_viewUpdateRecordsButtonActionPerformed

    private void logoutRecordsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutRecordsMenuActionPerformed
        // TODO add your handling code here:
        Date timeOfLogout = new Date();
        try {
            //Using BufferedWriter as opposed to FileWriter due to performance being better
            BufferedWriter writer = new BufferedWriter(new FileWriter("ppmData.csv", true));

            // Write data to the file
            writer.append("\n" + "Time user logged out" + "\n" +
                    timeOfLogout + "\n");
            //writer.newLine(); // Add a newline character

            

            // Close the BufferedWriter to flush and close the underlying FileWriter
            writer.close();

            JOptionPane.showMessageDialog(null,"Logout recorded, .");
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        System.exit(0);
    }//GEN-LAST:event_logoutRecordsMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel heading1;
    private javax.swing.JLabel heading2;
    private javax.swing.JButton logoutRecordsMenu;
    private javax.swing.JLabel recordsTitle;
    private javax.swing.JButton viewUpdateRecordsButton;
    // End of variables declaration//GEN-END:variables
}
